apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: harshavardhan303/cicd-e2e:1 # Replace ' ' with the build number
        ports:
        - containerPort: 8282
